# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - env-build

      - run:
          name: setup env
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install ./[tensorboard,tests]
      - save_cache:
          paths:
            - ./venv
          key: env-build

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test --verbose --runslow hypertunity
      - store_artifacts:
          path: test-reports
          destination: test-reports
